[
    {
        "problem_type": "Assertion Error",
        "test_name": "test_event_as_dict",
        "language": "Python",
        "filename": "mergify_engine/tests/unit/test_events_db.py",
        "lineno": 760,
        "error": "AssertionError",
        "test_framework": "pytest",
        "stack_trace": "assert {'deleted_by': {'id': 987, 'name': 'cell', 'type': <GithubAuthenticatedActorType.USER: 'user'>}, 'deleted_by_id': 987, 'id': 1, 'pull_request': None, 'received_at': <ANY>, 'repository': {'archived': False, 'default_branch': 'main', 'full_name': 'Mergifyio/mergify-engine', 'id': 0, ...}} != {'deleted_by': {'id': 987, 'name': 'cell', 'type': <GithubAuthenticatedActorType.USER: 'user'>}, 'deleted_by_id': 987, 'id': 1, 'pull_request': None, 'received_at': '', 'repository': {'archived': False, 'ci_issue_prefix': None, 'default_branch': 'main', 'full_name': 'Mergifyio/mergify-engine', ...}}"
    }
]