2023-10-23T08:39:16.8912871Z ##[group]Run Mergifyio/add-linear-author-as-reviewer@main
2023-10-23T08:39:16.8913680Z with:
2023-10-23T08:39:16.8914367Z   GITHUB_TOKEN: ***
2023-10-23T08:39:16.8915051Z   LINEAR_API_KEY: ***
2023-10-23T08:39:16.8918203Z   EMAIL_MAPPING: jd@mergify.com jd
sileht@mergify.com sileht
fabien.martinet@mergify.com Syffe
alexandre.gaubert@mergify.com AlexandreGaubert
charly.laurent@mergify.com DouglasBlackwood
guillaume.risbourg@mergify.com Greesb
leo.ecrepont@mergify.com lecrepont01
damien.couppe@mergify.com Kontrolix
samuel.billaud@mergify.com samuelbillaud
2023-10-23T08:39:16.8921230Z ##[endgroup]
2023-10-23T08:39:16.9262533Z ##[group]Run python3 -m venv venv
2023-10-23T08:39:16.9263213Z [36;1mpython3 -m venv venv[0m
2023-10-23T08:39:16.9263757Z [36;1mvenv/bin/pip install httpx[0m
2023-10-23T08:39:16.9265259Z [36;1mvenv/bin/python /home/runner/work/_actions/Mergifyio/add-linear-author-as-reviewer/main/linear-extract-reviewers.py >> $GITHUB_OUTPUT[0m
2023-10-23T08:39:16.9328395Z shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
2023-10-23T08:39:16.9329208Z env:
2023-10-23T08:39:16.9329963Z   INPUT_LINEAR_API_KEY: ***
2023-10-23T08:39:16.9333017Z   INPUT_EMAIL_MAPPING: jd@mergify.com jd
sileht@mergify.com sileht
fabien.martinet@mergify.com Syffe
alexandre.gaubert@mergify.com AlexandreGaubert
charly.laurent@mergify.com DouglasBlackwood
guillaume.risbourg@mergify.com Greesb
leo.ecrepont@mergify.com lecrepont01
damien.couppe@mergify.com Kontrolix
samuel.billaud@mergify.com samuelbillaud
2023-10-23T08:39:16.9336588Z   INPUT_PULL_REQUEST_BODY: Fixes MRGFY-1672

Change-Id: Icc856f9acf20252e1e8cddad0ba196229636b3fd
2023-10-23T08:39:16.9337581Z ##[endgroup]
2023-10-23T08:39:21.5597962Z Collecting httpx
2023-10-23T08:39:21.6763227Z   Downloading httpx-0.25.0-py3-none-any.whl (75 kB)
2023-10-23T08:39:21.7122934Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.7/75.7 KB 2.3 MB/s eta 0:00:00
2023-10-23T08:39:21.7777611Z Collecting httpcore<0.19.0,>=0.18.0
2023-10-23T08:39:21.7930502Z   Downloading httpcore-0.18.0-py3-none-any.whl (76 kB)
2023-10-23T08:39:21.8084005Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.0/76.0 KB 5.4 MB/s eta 0:00:00
2023-10-23T08:39:21.8533756Z Collecting certifi
2023-10-23T08:39:21.8686293Z   Downloading certifi-2023.7.22-py3-none-any.whl (158 kB)
2023-10-23T08:39:21.8919737Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 158.3/158.3 KB 7.2 MB/s eta 0:00:00
2023-10-23T08:39:21.9245582Z Collecting idna
2023-10-23T08:39:21.9399984Z   Downloading idna-3.4-py3-none-any.whl (61 kB)
2023-10-23T08:39:21.9482793Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.5/61.5 KB 8.5 MB/s eta 0:00:00
2023-10-23T08:39:21.9738673Z Collecting sniffio
2023-10-23T08:39:21.9890812Z   Downloading sniffio-1.3.0-py3-none-any.whl (10 kB)
2023-10-23T08:39:22.0263351Z Collecting h11<0.15,>=0.13
2023-10-23T08:39:22.0414375Z   Downloading h11-0.14.0-py3-none-any.whl (58 kB)
2023-10-23T08:39:22.0507339Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 KB 6.8 MB/s eta 0:00:00
2023-10-23T08:39:22.0968839Z Collecting anyio<5.0,>=3.0
2023-10-23T08:39:22.1122330Z   Downloading anyio-4.0.0-py3-none-any.whl (83 kB)
2023-10-23T08:39:22.1230934Z      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.1/83.1 KB 8.5 MB/s eta 0:00:00
2023-10-23T08:39:22.1728956Z Collecting exceptiongroup>=1.0.2
2023-10-23T08:39:22.1882633Z   Downloading exceptiongroup-1.1.3-py3-none-any.whl (14 kB)
2023-10-23T08:39:22.2507552Z Installing collected packages: sniffio, idna, h11, exceptiongroup, certifi, anyio, httpcore, httpx
2023-10-23T08:39:22.5752413Z Successfully installed anyio-4.0.0 certifi-2023.7.22 exceptiongroup-1.1.3 h11-0.14.0 httpcore-0.18.0 httpx-0.25.0 idna-3.4 sniffio-1.3.0
2023-10-23T08:39:22.7606756Z {'query': 'query { MRGFY_1672: issue(id: "MRGFY-1672") { creator { email } }  }'}
2023-10-23T08:39:37.9369436Z Traceback (most recent call last):
2023-10-23T08:39:37.9371048Z   File "/home/runner/work/engine/engine/venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
2023-10-23T08:39:37.9372502Z     yield
2023-10-23T08:39:37.9373556Z   File "/home/runner/work/engine/engine/venv/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 126, in read
2023-10-23T08:39:37.9374716Z     return self._sock.recv(max_bytes)
2023-10-23T08:39:37.9375378Z   File "/usr/lib/python3.10/ssl.py", line 1259, in recv
2023-10-23T08:39:37.9375961Z     return self.read(buflen)
2023-10-23T08:39:37.9376491Z   File "/usr/lib/python3.10/ssl.py", line 1132, in read
2023-10-23T08:39:37.9377069Z     return self._sslobj.read(len)
2023-10-23T08:39:37.9377602Z TimeoutError: The read operation timed out
2023-10-23T08:39:37.9378018Z 
2023-10-23T08:39:37.9378405Z The above exception was the direct cause of the following exception:
2023-10-23T08:39:37.9378975Z 
2023-10-23T08:39:37.9379209Z Traceback (most recent call last):
2023-10-23T08:39:37.9380479Z   File "/home/runner/work/engine/engine/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
2023-10-23T08:39:37.9381591Z     yield
2023-10-23T08:39:37.9382668Z   File "/home/runner/work/engine/engine/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 228, in handle_request
2023-10-23T08:39:37.9383792Z     resp = self._pool.handle_request(req)
2023-10-23T08:39:37.9385041Z   File "/home/runner/work/engine/engine/venv/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 262, in handle_request
2023-10-23T08:39:37.9386128Z     raise exc
2023-10-23T08:39:37.9387239Z   File "/home/runner/work/engine/engine/venv/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 245, in handle_request
2023-10-23T08:39:37.9388476Z     response = connection.handle_request(request)
2023-10-23T08:39:37.9389749Z   File "/home/runner/work/engine/engine/venv/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 103, in handle_request
2023-10-23T08:39:37.9390902Z     return self._connection.handle_request(request)
2023-10-23T08:39:37.9392156Z   File "/home/runner/work/engine/engine/venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 133, in handle_request
2023-10-23T08:39:37.9394289Z     raise exc
2023-10-23T08:39:37.9395285Z   File "/home/runner/work/engine/engine/venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 111, in handle_request
2023-10-23T08:39:37.9396524Z     ) = self._receive_response_headers(**kwargs)
2023-10-23T08:39:37.9397736Z   File "/home/runner/work/engine/engine/venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 176, in _receive_response_headers
2023-10-23T08:39:37.9398834Z     event = self._receive_event(timeout=timeout)
2023-10-23T08:39:37.9399965Z   File "/home/runner/work/engine/engine/venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 212, in _receive_event
2023-10-23T08:39:37.9400955Z     data = self._network_stream.read(
2023-10-23T08:39:37.9401988Z   File "/home/runner/work/engine/engine/venv/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 124, in read
2023-10-23T08:39:37.9402935Z     with map_exceptions(exc_map):
2023-10-23T08:39:37.9403494Z   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
2023-10-23T08:39:37.9404083Z     self.gen.throw(typ, value, traceback)
2023-10-23T08:39:37.9405171Z   File "/home/runner/work/engine/engine/venv/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
2023-10-23T08:39:37.9406132Z     raise to_exc(exc) from exc
2023-10-23T08:39:37.9406588Z httpcore.ReadTimeout: The read operation timed out
2023-10-23T08:39:37.9406963Z 
2023-10-23T08:39:37.9407273Z The above exception was the direct cause of the following exception:
2023-10-23T08:39:37.9407740Z 
2023-10-23T08:39:37.9407887Z Traceback (most recent call last):
2023-10-23T08:39:37.9408952Z   File "/home/runner/work/_actions/Mergifyio/add-linear-author-as-reviewer/main/linear-extract-reviewers.py", line 52, in <module>
2023-10-23T08:39:37.9409883Z     main()
2023-10-23T08:39:37.9410783Z   File "/home/runner/work/_actions/Mergifyio/add-linear-author-as-reviewer/main/linear-extract-reviewers.py", line 38, in main
2023-10-23T08:39:37.9411991Z     responses = linear.post("/graphql", json=query).json()
2023-10-23T08:39:37.9413063Z   File "/home/runner/work/engine/engine/venv/lib/python3.10/site-packages/httpx/_client.py", line 1132, in post
2023-10-23T08:39:37.9413940Z     return self.request(
2023-10-23T08:39:37.9414852Z   File "/home/runner/work/engine/engine/venv/lib/python3.10/site-packages/httpx/_client.py", line 814, in request
2023-10-23T08:39:37.9415923Z     return self.send(request, auth=auth, follow_redirects=follow_redirects)
2023-10-23T08:39:37.9417065Z   File "/home/runner/work/engine/engine/venv/lib/python3.10/site-packages/httpx/_client.py", line 901, in send
2023-10-23T08:39:37.9417950Z     response = self._send_handling_auth(
2023-10-23T08:39:37.9419036Z   File "/home/runner/work/engine/engine/venv/lib/python3.10/site-packages/httpx/_client.py", line 929, in _send_handling_auth
2023-10-23T08:39:37.9420044Z     response = self._send_handling_redirects(
2023-10-23T08:39:37.9421164Z   File "/home/runner/work/engine/engine/venv/lib/python3.10/site-packages/httpx/_client.py", line 966, in _send_handling_redirects
2023-10-23T08:39:37.9422209Z     response = self._send_single_request(request)
2023-10-23T08:39:37.9423341Z   File "/home/runner/work/engine/engine/venv/lib/python3.10/site-packages/httpx/_client.py", line 1002, in _send_single_request
2023-10-23T08:39:37.9424365Z     response = transport.handle_request(request)
2023-10-23T08:39:37.9425533Z   File "/home/runner/work/engine/engine/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 227, in handle_request
2023-10-23T08:39:37.9426536Z     with map_httpcore_exceptions():
2023-10-23T08:39:37.9427086Z   File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
2023-10-23T08:39:37.9427663Z     self.gen.throw(typ, value, traceback)
2023-10-23T08:39:37.9428846Z   File "/home/runner/work/engine/engine/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
2023-10-23T08:39:37.9429903Z     raise mapped_exc(message) from exc
2023-10-23T08:39:37.9430498Z httpx.ReadTimeout: The read operation timed out
2023-10-23T08:39:37.9584422Z ##[error]Process completed with exit code 1.
